/* oxlint-disable typescript/no-base-to-string -- request values are normalized by the local text helper. */
import { authenticatedAccess } from '@/lib/auth-access'; import { trustedMutationOrigin } from '@/lib/auth-config'; import { getD1 } from '@/db';
export async function POST(request:Request){const access=await authenticatedAccess();if(!access||access.mustChangePassword||access.role!=='manager')return Response.json({error:'Manager access required.'},{status:403});if(!trustedMutationOrigin(request.headers.get('origin')))return Response.json({error:'Invalid request origin.'},{status:403});const body=await request.json() as Record<string,unknown>, action=String(body.action||''), db=getD1(), now=new Date().toISOString(), text=(v:unknown,n=2000)=>typeof v==='string'?v.trim().slice(0,n):'';
 if(action==='requestReimbursement')await db.prepare(`INSERT INTO csil_reimbursements(id,household_id,claimant_id,expense_date,description,amount,status,created_at) VALUES(?,'default',?,?,?,?,'pending',?)`).bind(crypto.randomUUID(),text(body.claimantId,100),text(body.expenseDate,10),text(body.description,500),Number(body.amount),now).run();
 else if(action==='decideReimbursement')await db.prepare(`UPDATE csil_reimbursements SET status=?,decided_by=?,decided_at=?,decision_note=? WHERE id=? AND status='pending'`).bind(body.status==='approved'?'approved':'declined',access.memberId,now,text(body.note,500),text(body.id,100)).run();
 else if(action==='recordConsent')await db.prepare(`INSERT INTO csil_consents(id,household_id,subject_member_id,purpose,status,granted_at,expires_on,recorded_by,created_at) VALUES(?,'default',?,?,'granted',?,?,?,?)`).bind(crypto.randomUUID(),text(body.memberId,100)||null,text(body.purpose,500),now,text(body.expiresOn,10)||null,access.memberId,now).run();
 else if(action==='withdrawConsent')await db.prepare(`UPDATE csil_consents SET status='withdrawn',withdrawn_at=? WHERE id=?`).bind(now,text(body.id,100)).run();
 else if(action==='saveEmergencyPlan')await db.prepare(`INSERT INTO csil_emergency_plan(household_id,primary_contact,backup_contacts,agency_plan,essential_care,escalation,last_reviewed_on,updated_by,updated_at) VALUES('default',?,?,?,?,?,?,?,?) ON CONFLICT(household_id) DO UPDATE SET primary_contact=excluded.primary_contact,backup_contacts=excluded.backup_contacts,agency_plan=excluded.agency_plan,essential_care=excluded.essential_care,escalation=excluded.escalation,last_reviewed_on=excluded.last_reviewed_on,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).bind(text(body.primaryContact,500),text(body.backupContacts),text(body.agencyPlan),text(body.essentialCare),text(body.escalation),text(body.lastReviewedOn,10)||null,access.memberId,now).run();
 else if(action==='saveGovernance'){const years=Math.max(4,Math.min(25,Number(body.retentionYears)||7));let mapping='{}';try{const value=JSON.parse(text(body.templateJson,10000)||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw 0;mapping=JSON.stringify(value);}catch{return Response.json({error:'Template mapping must be a JSON object.'},{status:400});}await db.prepare(`UPDATE household_settings SET csil_financial_retention_years=?,csil_authority_template_json=?,updated_at=? WHERE household_id='default'`).bind(years,mapping,now).run();}
 else return Response.json({error:'Unknown action.'},{status:400}); await db.prepare(`INSERT INTO audit_log(id,chore_id,actor_id,action,detail,created_at) VALUES(?,NULL,?,'csil_admin_update',?,?)`).bind(crypto.randomUUID(),access.memberId,action,now).run();return Response.json({ok:true});}
