/* oxlint-disable typescript/no-base-to-string -- FormData values are narrowed before use. */
import { mkdir, writeFile } from 'node:fs/promises'; import { resolve } from 'node:path';
import { authenticatedAccess } from '@/lib/auth-access'; import { trustedMutationOrigin } from '@/lib/auth-config'; import { getD1 } from '@/db';
import { encryptCsilDocument } from '@/lib/csil-crypto'; import { extractClientNoteText } from '@/lib/ocr'; import { validateUpload } from '@/lib/operations';
export const runtime='nodejs';
export async function POST(request:Request){ const access=await authenticatedAccess(); if(!access||access.mustChangePassword||access.role!=='manager') return Response.json({error:'Manager access required.'},{status:403}); if(!trustedMutationOrigin(request.headers.get('origin'))) return Response.json({error:'Invalid request origin.'},{status:403});
 const form=await request.formData(), file=form.get('file'), expenseId=typeof form.get('expenseId')==='string'?String(form.get('expenseId')):''; if(!(file instanceof File)) return Response.json({error:'Choose a receipt image.'},{status:400}); const bytes=new Uint8Array(await file.arrayBuffer()); const problem=validateUpload(file.type,file.size,bytes); if(problem)return Response.json({error:problem},{status:400});
 let ocr=''; try{ocr=await extractClientNoteText(Buffer.from(bytes));}catch{/* OCR is best effort for financial documents */} let encrypted:Buffer; try{encrypted=encryptCsilDocument(Buffer.from(bytes));}catch(error){return Response.json({error:error instanceof Error?error.message:'Encryption unavailable.'},{status:503});}
 const id=crypto.randomUUID(), stored=`csil-${id}.enc`, root=resolve(process.env.UPLOAD_PATH||'/data/uploads'), target=resolve(root,stored); if(!target.startsWith(`${root}\\`)&&!target.startsWith(`${root}/`))return Response.json({error:'Invalid path.'},{status:400}); await mkdir(root,{recursive:true}); await writeFile(target,encrypted,{flag:'wx',mode:0o600}); const now=new Date().toISOString(); await getD1().prepare(`INSERT INTO csil_documents(id,household_id,expense_id,kind,stored_name,original_name,mime_type,byte_size,ocr_text,uploaded_by,created_at) VALUES(?,'default',?,'receipt',?,?,?,?,?,?,?)`).bind(id,expenseId||null,stored,file.name.slice(0,255),file.type,file.size,ocr.slice(0,10000),access.memberId,now).run(); return Response.json({id,ocrText:ocr.slice(0,1000)},{status:201}); }
