'use client';
/* oxlint-disable jsx-a11y/label-has-associated-control, jsx-a11y/prefer-tag-over-role -- compact controls are nested and the status is dynamically announced. */
import { useState } from 'react'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input';
const box='rounded-2xl border border-[#dfe5dc] bg-white p-5', field='mt-1 min-h-11 w-full rounded-xl border border-[#d7dfd7] px-3 py-2 text-sm';
export function CsilOperationsPanel(){const [notice,setNotice]=useState('');const post=async(url:string,body:BodyInit,headers?:HeadersInit)=>{const response=await fetch(url,{method:'POST',body,headers});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');setNotice(data.imported!==undefined?`Imported ${data.imported}; matched ${data.matched}.`:'Saved.');};const json=(form:HTMLFormElement)=>post('/api/csil-admin',JSON.stringify(Object.fromEntries(new FormData(form))),{'Content-Type':'application/json'});
return <section className="mt-6 space-y-6" aria-labelledby="csil-ops"><h2 id="csil-ops" className="text-lg font-bold">CSIL records and continuity</h2>{notice&&<p role="status" className="rounded-xl bg-[#e8f1ec] p-3 text-sm">{notice}</p>}
<div className="grid gap-6 lg:grid-cols-2"><form className={box} onSubmit={e=>{e.preventDefault();void post('/api/csil-documents',new FormData(e.currentTarget)).catch(x=>setNotice(x.message));}}><h3 className="font-bold">Encrypted receipt capture + OCR</h3><p className="my-2 text-sm text-[#687873]">Images are AES-256-GCM encrypted before storage; extracted text supports search and audit preparation.</p><Input name="expenseId" placeholder="Expense ID (optional)" className="mb-2"/><Input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/><Button className="mt-3" type="submit">Encrypt and save receipt</Button></form>
<form className={box} onSubmit={async e=>{e.preventDefault();const file=new FormData(e.currentTarget).get('file');if(file instanceof File)void post('/api/csil-bank-import',await file.text(),{'Content-Type':'text/plain'}).catch(x=>setNotice(x.message));}}><h3 className="font-bold">Bank reconciliation import</h3><p className="my-2 text-sm text-[#687873]">Import provider-neutral CSV or OFX. Matching uses date and amount; no bank credentials leave your control.</p><Input name="file" type="file" accept=".csv,.ofx,text/csv" required/><Button className="mt-3" type="submit">Import transactions</Button></form></div>
<div className="grid gap-6 lg:grid-cols-2"><form className={box} onSubmit={e=>{e.preventDefault();void json(e.currentTarget).catch(x=>setNotice(x.message));}}><input type="hidden" name="action" value="saveEmergencyPlan"/><h3 className="font-bold">Emergency backup-care plan</h3>{['primaryContact','backupContacts','agencyPlan','essentialCare','escalation'].map(name=><label key={name} className="mt-2 block text-sm font-semibold">{name.replace(/([A-Z])/g,' $1')}<textarea name={name} className={field} rows={2}/></label>)}<label className="mt-2 block text-sm font-semibold">Last reviewed<Input name="lastReviewedOn" type="date"/></label><Button className="mt-3" type="submit">Save plan</Button></form>
<form className={box} onSubmit={e=>{e.preventDefault();void json(e.currentTarget).catch(x=>setNotice(x.message));}}><input type="hidden" name="action" value="saveGovernance"/><h3 className="font-bold">Retention and authority template</h3><label className="mt-2 block text-sm font-semibold">Financial retention years<Input name="retentionYears" type="number" min="4" max="25" defaultValue="7"/></label><label className="mt-2 block text-sm font-semibold">Authority field mapping (JSON)<textarea name="templateJson" className={field} rows={7} defaultValue="{}"/></label><Button className="mt-3" type="submit">Save governance</Button><a className="ml-3 inline-flex min-h-11 items-center text-sm font-semibold text-[#287b6f]" href={`/api/csil-year-end?year=${new Date().getFullYear()}`}>Download year-end package</a></form></div>
<div className="grid gap-6 lg:grid-cols-2"><form className={box} onSubmit={e=>{e.preventDefault();void json(e.currentTarget).catch(x=>setNotice(x.message));}}><input type="hidden" name="action" value="requestReimbursement"/><h3 className="font-bold">Reimbursement request</h3><Input name="claimantId" placeholder="Worker member ID" required/><Input name="expenseDate" type="date" required/><Input name="description" placeholder="Description" required/><Input name="amount" type="number" step="0.01" min="0.01" required/><Button className="mt-3" type="submit">Submit for approval</Button></form><form className={box} onSubmit={e=>{e.preventDefault();void json(e.currentTarget).catch(x=>setNotice(x.message));}}><input type="hidden" name="action" value="recordConsent"/><h3 className="font-bold">Privacy consent record</h3><Input name="memberId" placeholder="Member ID (optional)"/><Input name="purpose" placeholder="Purpose and data scope" required/><Input name="expiresOn" type="date"/><Button className="mt-3" type="submit">Record consent</Button></form></div></section>}
