// Professional icon mapping for dashboard widgets. Keyed by widget id;
// ids shared across roles reuse the same icon.

import {
  Activity,
  Award,
  BadgeCheck,
  Bell,
  CalendarClock,
  CalendarDays,
  Camera,
  ClipboardList,
  Clock,
  FileCheck,
  FileDown,
  Gauge,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  History,
  Home,
  Inbox,
  LayoutGrid,
  Link,
  ListTodo,
  Megaphone,
  MessageSquareText,
  NotebookText,
  PenLine,
  PieChart,
  Pill,
  Shield,
  ShieldAlert,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  StickyNote,
  Timer,
  TriangleAlert,
  UserCheck,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export const WIDGET_ICONS: Record<string, LucideIcon> = {
  // Shared / manager
  hero: Home,
  metrics: Gauge,
  decisions: Bell,
  priorities: ClipboardList,
  attendance: UserCheck,
  safety: ShieldAlert,
  workload: Activity,
  handofflog: History,
  funding: Wallet,
  review: FileCheck,
  certs: BadgeCheck,
  handoffs: MessageSquareText,
  pulse: HeartPulse,
  photos: Camera,
  activity: History,
  quickactions: Sparkles,
  payroll: FileDown,
  hralerts: ClipboardList,
  hrexpanding: Users,
  team: Users,
  inboxpreview: Inbox,
  schedulepreview: CalendarDays,
  // Worker
  announcements: Megaphone,
  coverage: HeartHandshake,
  timeclock: Clock,
  shiftbrief: NotebookText,
  mytasks: ListTodo,
  notes: StickyNote,
  snapshot: PieChart,
  handoffform: PenLine,
  safetyform: TriangleAlert,
  safetylog: Shield,
  schedule: CalendarDays,
  weektime: Timer,
  quicklinks: Link,
  // Viewer
  onshift: Users,
  duetoday: CalendarClock,
  // Care plan
  medsround: Pill,
  aboutme: HandHeart,
  appointments: Stethoscope,
  supplies: ShoppingCart,
  kudos: Award,
};

/** Icon for a widget id — falls back to a generic grid icon. */
export function widgetIcon(id: string): LucideIcon {
  return WIDGET_ICONS[id] ?? LayoutGrid;
}
